
function ai_types() {

    /*
    {
        idle: true | false,

        percent_vehicle [0 1],
		percent_bot [0 1],
        percent_air [0 1],
        percent_naval [0 1],
		percent_orbital [0 1],

        personality_tags: [<string>, <string>, ...],

        metal_drain_check [0 1],
        energy_drain_check [0 1],
        metal_demand_check [0 1],
        energy_demand_check [0 1],

        micro_type 0:none | 1:platoon | 2:squad,

        go_for_the_kill: true | false,
        priority_scout_metal_spots: true | false,
        enable_commander_danger_responses: true | false,

        neural_data_mod: [0 ... )
        adv_eco_mod: [0 ... )
        adv_eco_mod_alone: [0 ... )
        factory_build_delay_min: [0 ... ] (in seconds)
        factory_build_delay_max: [0 ... ] (in seconds)
        unable_to_expand_delay: [0 ... ] (in seconds)
        per_expansion_delay: [0 ... ] (in seconds)
        fabber_to_factory_ratio_basic: [0 ... ]
        fabber_to_factory_ratio_advanced: [0 ... ]
        fabber_alone_on_planet_mod: [0 ... ]
        basic_to_advanced_factory_ratio: [0 ... ]
        factory_alone_on_planet_mod: [0 ... ]
        min_basic_fabbers: [0 ... ]
        max_basic_fabbers: [0 ... ]
        min_advanced_fabbers: [0 ... ]
        max_advanced_fabbers: [0 ... ]
    }
    */

    var paAI =
    {
        'Idle':
        {
            display_name: '!LOC:Idle',
            idle: true
        },
        'Easy':
        {
            display_name: '!LOC:Easy',
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags:
            [
                "Default",
                "SlowerExpansion"
            ],
            metal_drain_check: 0.14,
            energy_drain_check: 0.25,
            metal_demand_check: 0.21,
            energy_demand_check: 0.3,
            go_for_the_kill: false,
            priority_scout_metal_spots: false,
            enable_commander_danger_responses: false,
            micro_type: 0,
            neural_data_mod: 2.0,
            adv_eco_mod: 3.0,
            adv_eco_mod_alone: 3.0,
            factory_build_delay_min: 60,
            factory_build_delay_max: 180,
            unable_to_expand_delay: 900,
            per_expansion_delay: 900,
            fabber_to_factory_ratio_basic: 2.0,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 1.0,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 1.0,
            min_basic_fabbers: 5,
            max_basic_fabbers: 15,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 20
        },
        'Normal':
        {
            display_name: '!LOC:Normal',
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags:
            [
                "Default",
                "SlowerExpansion"
            ],
            metal_drain_check: 0.24,
            energy_drain_check: 0.35,
            metal_demand_check: 0.41,
            energy_demand_check: 0.5,
            micro_type: 1,
            go_for_the_kill: true,
            priority_scout_metal_spots: true,
            enable_commander_danger_responses: true,
            neural_data_mod: 1.5,
            adv_eco_mod: 1.0,
            adv_eco_mod_alone: 1.5,
            factory_build_delay_min: 10,
            factory_build_delay_max: 15,
            unable_to_expand_delay: 60,
            per_expansion_delay: 120,
            fabber_to_factory_ratio_basic: 1.5,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 1.5,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.75,
            min_basic_fabbers: 3,
            max_basic_fabbers: 10,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 20
        },
        'NormalPlus':
        {
            display_name: "!LOC:Normal" + "+",
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags: 
            [
              "Default",
              "SlowerExpansion"
            ],
            metal_drain_check: 0.24,
            energy_drain_check: 0.35,
            metal_demand_check: 0.41,
            energy_demand_check: 0.5,
            micro_type: 1,
            go_for_the_kill: true,
            priority_scout_metal_spots: false,
            enable_commander_danger_responses: true,
            neural_data_mod: 1.5,
            adv_eco_mod: 1.0,
            adv_eco_mod_alone: 1.0,
            factory_build_delay_min: 1,
            factory_build_delay_max: 3,
            unable_to_expand_delay: 0,
            per_expansion_delay: 0,
            fabber_to_factory_ratio_basic: 1.0,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 2.0,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 2,
            max_basic_fabbers: 6,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 20,
            starting_location_evaluation_radius: 200,
        },
        'Hard':
        {
            display_name: '!LOC:Hard',
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags:
            [
                "Default",
            ],
            metal_drain_check: 0.34,
            energy_drain_check: 0.45,
            metal_demand_check: 0.51,
            energy_demand_check: 0.6,
            micro_type: 1,
            go_for_the_kill: true,
            priority_scout_metal_spots: true,
            enable_commander_danger_responses: true,
            neural_data_mod: 1.5,
            adv_eco_mod: 1.1,
            adv_eco_mod_alone: 1.0,
            factory_build_delay_min: 0,
            factory_build_delay_max: 3,
            unable_to_expand_delay: 0,
            per_expansion_delay: 0,
            fabber_to_factory_ratio_basic: 1.0,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 2.0,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 2,
            max_basic_fabbers: 6,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 20,
            starting_location_evaluation_radius: 200
        },
        'Relentless':
        {
            display_name: '!LOC:Relentless',
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags:
            [
                "Default",
                "PreventsWaste"
            ],
            metal_drain_check: 0.44,
            energy_drain_check: 0.55,
            metal_demand_check: 0.61,
            energy_demand_check: 0.7,
            micro_type: 2,
            go_for_the_kill: true,
            priority_scout_metal_spots: true,
            enable_commander_danger_responses: true,
            neural_data_mod: 1.2,
            adv_eco_mod: 1.2,
            adv_eco_mod_alone: 0.95,
            factory_build_delay_min: 0,
            unable_to_expand_delay: 0,
            per_expansion_delay: 0,
            fabber_to_factory_ratio_basic: 1.0,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 2.0,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 2,
            max_basic_fabbers: 10,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 30,
            starting_location_evaluation_radius: 300
        },
        'Absurd':
        {
            display_name: '!LOC:Absurd',
            percent_vehicle: 0.45,
            percent_bot: 0.25,
            percent_air: 0.2,
            percent_naval: 0.05,
            percent_orbital: 0.05,
            personality_tags:
            [
                "Default",
                "PreventsWaste"
            ],
            metal_drain_check: 0.54,
            energy_drain_check: 0.65,
            metal_demand_check: 0.71,
            energy_demand_check: 0.8,
            micro_type: 2,
            go_for_the_kill: true,
            priority_scout_metal_spots: true,
            enable_commander_danger_responses: true,
            neural_data_mod: 1.0,
            unable_to_expand_delay: 0,
            per_expansion_delay: 0,
            factory_build_delay_min: 0,
            adv_eco_mod: 1.3,
            adv_eco_mod_alone: 0.85,
            fabber_to_factory_ratio_basic: 1.0,
            fabber_to_factory_ratio_advanced: 1.0,
            fabber_alone_on_planet_mod: 2.0,
            basic_to_advanced_factory_ratio: 0,
            factory_alone_on_planet_mod: 0.5,
            min_basic_fabbers: 2,
            max_basic_fabbers: 20,
            min_advanced_fabbers: 3,
            max_advanced_fabbers: 50,
            starting_location_evaluation_radius: 400
        },
        'Random': 
        {
            display_name: "!LOC:Random"
        },
    };

  var quellerAIBaseValues = {
    'qCasual': {
      ai_path: "/pa/ai_queller/q_casual",
      display_name: "!LOC:Q-Casual",
      metal_drain_check: 0.64,
      energy_drain_check: 0.77,
      metal_demand_check: 0.95,
      energy_demand_check: 0.92,
      micro_type: 0,
      go_for_the_kill: false,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: false,
      neural_data_mod: 2,
      adv_eco_mod: 0.5,
      adv_eco_mod_alone: 0,
      factory_build_delay_min: 0,
      factory_build_delay_max: 12,
      per_expansion_delay: 60,
      personality_tags: ["queller"],
      min_basic_fabbers: 10,
      min_advanced_fabbers: 3,
    },
    'qBronze': {
      ai_path: "/pa/ai_queller/q_bronze",
      display_name: "!LOC:Q-Bronze",
      metal_drain_check: 0.54,
      energy_drain_check: 0.77,
      metal_demand_check: 0.95,
      energy_demand_check: 0.92,
      micro_type: 0,
      go_for_the_kill: false,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1.6,
      adv_eco_mod: 0.5,
      adv_eco_mod_alone: 0,
      factory_build_delay_min: 0,
      factory_build_delay_max: 6,
      personality_tags: ["queller"],
      min_basic_fabbers: 5,
      min_advanced_fabbers: 3,
    },
    'qSilver': {
      ai_path: "/pa/ai_queller/q_silver",
      display_name: "!LOC:Q-Silver",
      metal_drain_check: 0.54,
      energy_drain_check: 0.77,
      metal_demand_check: 0.95,
      energy_demand_check: 0.92,
      micro_type: 1,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1.45,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller"],
      min_basic_fabbers: 4,
      min_advanced_fabbers: 3,
    },
    'qGold': {
      ai_path: "/pa/ai_queller/q_gold",
      display_name: "!LOC:Q-Gold",
      metal_drain_check: 0.54,
      energy_drain_check: 0.77,
      metal_demand_check: 0.85,
      energy_demand_check: 0.92,
      micro_type: 1,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1.3,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 2,
    },
    'qPlatinum': {
      ai_path: "/pa/ai_queller/q_platinum",
      display_name: "!LOC:Q-Platinum",
      metal_drain_check: 0.54,
      energy_drain_check: 0.77,
      metal_demand_check: 0.85,
      energy_demand_check: 0.92,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1.15,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller"],
      min_basic_fabbers: 2,
      min_advanced_fabbers: 2,
    },
    'qUber': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUber1v1': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber 1v1",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1.35,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "lateorbital"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberAir': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Air",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "air"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberBot': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Bot",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "bot"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberFFA': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Free-For-All",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 0.85,
      adv_eco_mod: 0.75,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "ffa"],
      min_basic_fabbers: 4,
      min_advanced_fabbers: 1,
    },
    'qUberLand': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Land",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "land"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberOrbital': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Orbital",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "orbital"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberRush': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Rush",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.99,
      energy_demand_check: 0.99,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 2,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "lateorbital"],
      min_basic_fabbers: 2,
      min_advanced_fabbers: 1,
    },
    'qUberTank': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Tank",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.8,
      energy_demand_check: 0.8,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller", "tank"],
      min_basic_fabbers: 3,
      min_advanced_fabbers: 1,
    },
    'qUberTurtle': {
      ai_path: "/pa/ai_queller/q_uber",
      display_name: "!LOC:Q-Uber Turtle",
      metal_drain_check: 0.54,
      energy_drain_check: 0.72,
      metal_demand_check: 0.54,
      energy_demand_check: 0.72,
      micro_type: 2,
      go_for_the_kill: true,
      priority_scout_metal_spots: true,
      enable_commander_danger_responses: true,
      neural_data_mod: 1,
      adv_eco_mod: 1,
      adv_eco_mod_alone: 0,
      personality_tags: ["queller"],
      min_basic_fabbers: 4,
      min_advanced_fabbers: 1,
    },
  };

  var quellerAI = _.mapValues(
    quellerAIBaseValues,
    function (personality, name) {
      var result = _.assign(_.clone(paAI.Absurd), personality);
      result.name = name;
      return result;
    }
  );

  var aiPersonalities = api.content.usingTitans()
    ? _.merge(paAI, quellerAI)
    : paAI;

  _.forEach(aiPersonalities, function (element, key) {
    aiPersonalities[key]["name"] = key;
  });

  return aiPersonalities;
}
